package com.tweetapp.dynamo.entity;

import java.util.Date;
import java.util.List;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.tweetapp.dto.Reply;




@DynamoDBTable(tableName = "tweets")
public class Tweet {

	public String getTweetId() {
		return tweetId;
	}
	public void setTweetId(String tweetId) {
		this.tweetId = tweetId;
	}
	public String getUserTweetId() {
		return userTweetId;
	}
	public void setUserTweetId(String userTweetId) {
		this.userTweetId = userTweetId;
	}
	public String getTweet() {
		return tweet;
	}
	public void setTweet(String tweet) {
		this.tweet = tweet;
	}
	public Long getLike() {
		return like;
	}
	public void setLike(Long like) {
		this.like = like;
	}
	public List<Reply> getReply() {
		return reply;
	}
	public void setReply(List<Reply> reply) {
		this.reply = reply;
	}
	public String getDateOfPost() {
		return dateOfPost;
	}
	public void setDateOfPost(String dateOfPost) {
		this.dateOfPost = dateOfPost;
	}
	@DynamoDBHashKey(attributeName = "tweetId")
	@DynamoDBAutoGeneratedKey
	private String tweetId;

	@DynamoDBAttribute(attributeName = "userTweetId")
	private String userTweetId;
	@DynamoDBAttribute(attributeName = "tweet")
	private String tweet;

	@DynamoDBAttribute(attributeName = "like")
	private Long like;
	@DynamoDBAttribute(attributeName = "reply")
	private List<Reply> reply;
	
	@DynamoDBAttribute(attributeName = "dateOfPost")
	private String dateOfPost;

	
}
